# Worked on this in the 22-5-23 and 19-5-23 lectures

name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  env:
    PROJECT_ID: cd-demo-live-mrhq-prac-1 # TODO: update Google Cloud project id --> check google cloud run projects. ID column
    SERVICE: tasks-api # TODO: update Cloud Run service name
    REGION: australia-southeast2 # TODO: update Cloud Run service region --> https://cloud.google.com/run/docs/locations

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If required, update to the appropriate source folder
          source: ./

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
